package com.RestClientPalocs.Utils;

import java.awt.Color;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;

/**
	 *
	 * @author rez
	 */
	public class EventPanel extends javax.swing.JPanel {
		 private DateTimeFormatter timeFormatter = DateTimeFormatter.ofPattern("HH:mm:ss");
		 private DateTimeFormatter dateFormatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
	    /**
	     * Creates new form EventPanel
	     */
	    public EventPanel() {
	        initComponents();
	    }

	    /**
	     * This method is called from within the constructor to initialize the form.
	     * WARNING: Do NOT modify this code. The content of this method is always
	     * regenerated by the Form Editor.
	     */
	    @SuppressWarnings("unchecked")
	    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
	    private void initComponents() {

	        jLabel1 = new javax.swing.JLabel();
	        jLabel1.setForeground(Color.white);
	        jLabel2 = new javax.swing.JLabel();
	        jLabel2.setForeground(Color.white);
	        jLabel2.setHorizontalAlignment(javax.swing.JLabel.CENTER);
	        jLabel3 = new javax.swing.JLabel();
	        jLabel3.setForeground(Color.white);
	        jLabel4 = new javax.swing.JLabel();
	        jLabel4.setHorizontalAlignment(javax.swing.JLabel.CENTER);
	        jLabel4.setForeground(Color.white);
	        jLabel5 = new javax.swing.JLabel();
	        jLabel5.setForeground(Color.white);

	        setBackground(new java.awt.Color(31, 47, 97));

	        jLabel1.setText("EVENTS MANAGEMENT GROUP");

	        jLabel2.setText("Event");

	        jLabel3.setText(LocalDate.now().format(dateFormatter));

	        jLabel4.setText(LocalTime.now().format(timeFormatter));

	        jLabel5.setText("Please center your qr code in the frame ");

	        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
	        this.setLayout(layout);
	        layout.setHorizontalGroup(
	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(layout.createSequentialGroup()
	                .addGap(62, 62, 62)
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                    .addGroup(layout.createSequentialGroup()
	                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
	                        .addGap(32, 32, 32)
	                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
	                    .addComponent(jLabel5))
	                .addContainerGap(62, Short.MAX_VALUE))
	            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
	                .addGap(0, 0, Short.MAX_VALUE)
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
	                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
	                        .addGap(80, 80, 80))
	                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
	                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
	                        .addGap(127, 127, 127))))
	        );
	        layout.setVerticalGroup(
	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(layout.createSequentialGroup()
	                .addGap(30, 30, 30)
	                .addComponent(jLabel1)
	                .addGap(18, 18, 18)
	                .addComponent(jLabel2)
	                .addGap(26, 26, 26)
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(jLabel4)
	                    .addComponent(jLabel3))
	                .addGap(43, 43, 43)
	                .addComponent(jLabel5)
	                .addContainerGap(51, Short.MAX_VALUE))
	        );
	    }// </editor-fold>                        


	    // Variables declaration - do not modify                     
	    private javax.swing.JLabel jLabel1;
	    private javax.swing.JLabel jLabel2;
	    private javax.swing.JLabel jLabel3;
	    private javax.swing.JLabel jLabel4;
	    private javax.swing.JLabel jLabel5;
	    // End of variables declaration                   
		public void setEvent(String eventId) {
			// TODO Auto-generated method stub
			jLabel2.setText(eventId);	
		}

		public void setTime() {
			// TODO Auto-generated method stub
			jLabel4.setText(LocalTime.now().format(timeFormatter));
		}
	}

