package com.RestClientPalocs.Utils;

import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.Timer;

import java.awt.Color;
import java.awt.Component;
import java.awt.EventQueue;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.Rectangle;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.awt.image.ImageObserver;

import javax.swing.JPanel;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;

import com.RestClientPalocs.Gate.GateF;

public class WebcamPanel extends JPanel{
	
	private static final int offset_width = 120;
	private static final int offset_height = 36;
	private static final int height = 800;
	private static final int width = 480;
	private static final int side = 160;
	 // Variables declaration - do not modify                     
    // End of variables declaration     

	VideoCap videoCap;
	BufferedImage img;

	public WebcamPanel() {
		videoCap = new VideoCap();
		 initComponents();
	}
	
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                                                 
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(31, 47, 97));

        jLabel1.setText("jLabel1");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(233, 212, 27)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(120, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
    }// </editor-fold>                        


    // Variables declaration - do not modify                     
    private javax.swing.JLabel jLabel1;
    // End of variables declaration // </editor-fold>                        
               
	public void paintComponent(Graphics g) {
		super.paintComponent(g);
		g = getGraphics();
		//System.out.print("image printed \n");
		
		jLabel1.setIcon(new ImageIcon(cropImage(resize(img = videoCap.getOneFrame(),height/2,width/2),new Rectangle(side,side))));
	}

	/*public void setCamera(VideoCap cam) {
		// TODO Auto-generated method stub
		videoCap = cam;
		
	}*/
	public BufferedImage resize(BufferedImage img, int newW, int newH) {
		Image tmp = img.getScaledInstance(newW, newH, Image.SCALE_SMOOTH);
		BufferedImage dimg = new BufferedImage(newW, newH, BufferedImage.TYPE_INT_ARGB);

		Graphics2D g2d = dimg.createGraphics();
		g2d.drawImage(tmp, 0, 0, null);
		g2d.dispose();	
		return dimg;
	}
	
	public BufferedImage getImage() {
		return img;
	}
	
	private BufferedImage cropImage(BufferedImage src, Rectangle rect) {
		BufferedImage dest = src.getSubimage(offset_width,offset_height, rect.width, rect.height);
	      return dest; 
	   }
	
}

